image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Compile LaTeX
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Build latexmk Docker image"
          - export IMAGE_NAME=local/latexmk:$BITBUCKET_COMMIT
          - docker build --rm --tag $IMAGE_NAME .
          - echo "Compile LaTeX sources and make PDF"
          - >
            docker run --rm \
              -v "$(pwd):/local/source" \
              $IMAGE_NAME \
              make pdf
  branches:
    master:
      - step:
          name: Compile LaTeX
          services:
            - docker
          caches:
            - docker
          script:
            - echo "Build latexmk Docker image"
            - export IMAGE_NAME=local/latexmk:$BITBUCKET_COMMIT
            - docker build --rm --tag $IMAGE_NAME .
            - echo "Compile LaTeX sources and make PDF"
            - >
              docker run --rm \
                -v "$(pwd):/local/source" \
                $IMAGE_NAME \
                make pdf
          artifacts:
            - cv.pdf
      - step:
          name: Upload PDF via WeTransfer
          image: python:3.7-alpine
          services:
            - docker
          caches:
            - docker
          script:
            - apk add --no-cache git
            - echo "Clone transferwee repository"
            - git clone https://github.com/iamleot/transferwee.git
            - chmod +x transferwee/transferwee.py
            - pip install requests
            - echo "Upload PDF via WeTransfer"
            - >
              ./transferwee/transferwee.py upload \
                -m "New CV created" \
                -f $TRANSFERWEE_SENDER_EMAIL \
                -t $TRANSFERWEE_RECIPIENT_EMAIL -- \
                cv.pdf
