name: Compile curriculum vitae

on:
  push:
    paths:
      - '*.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX sources to PDF
        uses: xu-cheng/latex-action@master
        env:
          # Variables for placeholders in the sources
          CV_MOBILE: ${{ secrets.CV_MOBILE }}
          CV_EMAIL: ${{ secrets.CV_EMAIL }}
          CV_ADDRESS: ${{ secrets.CV_ADDRESS }}
          CV_BIRTH: ${{ secrets.CV_BIRTH }}
        with:
          root_file: cv.tex
          args: -pdf
